
import java.awt.HeadlessException;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.K;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sahibnoorsingh
 */
public class NEW_CHALLAN extends javax.swing.JFrame {
    int x,y;
    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null; 
    JCheckBox[] roll=new JCheckBox[100];
    int X,Y,K;
    /**
     * Creates new form NEW_CHALLAN
     */
    public NEW_CHALLAN()  {
            initComponents();
            setLocationRelativeTo(null);
            GetRecord1();
        //     GetRecord();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  /* private void GetRecord(){
        String sql="select * from ITEM_MASTER"; 
        try{
          con=Connect.ConnectDB();
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         jTable_item_master.setModel(DbUtils.resultSetToTableModel(rs));
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }*/

    
   
    

    
    
    
    
     private void reset() 
    {
    
    jTextFielPARTY_NAME.setText(""); 
    jTextFieldPARTY_CITY.setText("");
    jTextField_Address.setText("");
   jTextFieldITEM_NAME.setText("");
    jTextFieldserial_no.setText("");
    jTextField_Quantity.setText("");
    jTextFieldPrice.setText("");
    jDateChooser1.setDate(new Date());

    
    } 
    
    
  

     
      
    
    
    
    
    private void GetRecord1()
    {
     try{
      
   con=Connect.ConnectDB();
      String sql= "select NAME as NAME,ADDRESS as ADDRESS,CITY AS CITY from client_master";
      pst=con.prepareStatement(sql);
      rs=pst.executeQuery();
     jTable1_PARTYNAME_CITY.setModel(DbUtils.resultSetToTableModel(rs));
     
        }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(this,ex); 
        }
    }
    
/*private void GetRecord(){
        String sql="select ITEM_NAME as 'ITEM  NAME', SERIAL_NO as 'SERIAL_NO ',ADD_DATE AS DATE from ITEM_MASTER";
          try{
              con=Connect.ConnectDB();
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         jTable2_ITEMNAME_SERIAL_NO.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          

    }
}*/

 

 
 
 
 
 
 
 
 
 
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_challan = new javax.swing.JTextField();
        jTextField_Quantity = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPARTY_CITY = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldserial_no = new javax.swing.JTextField();
        jTextFielPARTY_NAME = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextField_Address = new javax.swing.JTextArea();
        jLabel_item = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonShowData = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFieldITEM_NAME = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelback_button = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_PARTYNAME_CITY = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("NEW CHALLAN"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Challan No.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Party Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Item Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address");

        jTextField_challan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_challan.setEnabled(false);

        jTextField_Quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText(" City");

        jTextFieldPARTY_CITY.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPARTY_CITY.setEnabled(false);
        jTextFieldPARTY_CITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPARTY_CITYActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Serial No.");

        jTextFieldserial_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFielPARTY_NAME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFielPARTY_NAME.setEnabled(false);
        jTextFielPARTY_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielPARTY_NAMEActionPerformed(evt);
            }
        });

        jTextField_Address.setColumns(20);
        jTextField_Address.setRows(5);
        jScrollPane3.setViewportView(jTextField_Address);

        jLabel_item.setText("....");
        jLabel_item.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_itemMouseClicked(evt);
            }
        });

        jButtonNew.setText("NEW");
        jButtonNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewMouseClicked(evt);
            }
        });
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonSave.setText("SAVE");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDelete.setText("DELETE");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonShowData.setText("SHOW DATA");
        jButtonShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShowDataMouseClicked(evt);
            }
        });
        jButtonShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowDataActionPerformed(evt);
            }
        });

        jTextFieldITEM_NAME.setColumns(20);
        jTextFieldITEM_NAME.setRows(5);
        jScrollPane4.setViewportView(jTextFieldITEM_NAME);

        jButton1.setText("Add Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jTextField_challan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFielPARTY_NAME, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPARTY_CITY, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextFieldserial_no, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Quantity, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_item)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_challan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielPARTY_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPARTY_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(85, 85, 85))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldserial_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel_item)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowData)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabelback_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-arrow.png"))); // NOI18N
        jLabelback_button.setText("Back");
        jLabelback_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelback_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelback_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelback_button)
                .addContainerGap())
        );

        jTable1_PARTYNAME_CITY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_PARTYNAME_CITY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_PARTYNAME_CITYMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_PARTYNAME_CITY);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel10.setText("By Party Name");

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel13.setText("CLIENT MASTER DATABASE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(349, 349, 349))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(581, 581, 581))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldPARTY_CITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPARTY_CITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPARTY_CITYActionPerformed

    private void jButtonShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowDataActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jLabelback_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelback_buttonMouseClicked
        // TODO add your handling code here:
        this.hide(); 
        Main_Menu obj=new Main_Menu();
         obj.setVisible(true);
         
    }//GEN-LAST:event_jLabelback_buttonMouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
           x=evt.getX();
           y=evt.getY();
           
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
                                 
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
         try
         {
            con=Connect.ConnectDB();
             
            
            
           PreparedStatement ps=con.prepareStatement("INSERT INTO new_challan(Party_Name,party_city,add_Date,Address,Serial_no,Quantity,Price)"
                    +"values(?,?,?,?,?,?,?,?)");

                
                ps.setString(1, jTextFielPARTY_NAME.getText());
                ps.setString(2, jTextFieldPARTY_CITY.getText());
                   
                SimpleDateFormat  dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                String addDate=dateFormat.format(jDateChooser1.getDate());
                ps.setString(3, addDate);
                
                ps.setString(4, jTextField_Address.getText());
                ps.setString(5,jTextFieldITEM_NAME.getText());
  
                ps.setString(6, jTextFieldserial_no.getText());
                ps.setString(7, jTextField_Quantity.getText());

            


                ps.setString(8, jTextFieldPrice.getText());
           


               ps.executeUpdate();

               // Show_Products_In_JTable();

                JOptionPane.showMessageDialog(null,"Data Saved");
     
 
            
           
           
           
         
         } 
        
         
         catch (SQLException ex ) {
            Logger.getLogger(NEW_CHALLAN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFielPARTY_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielPARTY_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielPARTY_NAMEActionPerformed

    private void jTable1_PARTYNAME_CITYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_PARTYNAME_CITYMouseClicked
        // TODO add your handling code here:
         try{
            con=Connect.ConnectDB();
            int row= jTable1_PARTYNAME_CITY.getSelectedRow();
            String table_click= jTable1_PARTYNAME_CITY.getModel().getValueAt(row, 0).toString();
            String sql= "select NAME AS NAME,ADDRESS AS ADDRESS , CITY AS CITY from client_master where name = '" + table_click + "'";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if(rs.next()){
       
                String add1=rs.getString("NAME");
                jTextFielPARTY_NAME.setText(add1);
                
                String add2=rs.getString("ADDRESS");
                jTextField_Address.setText(add2);
                
                String add3=rs.getString("CITY");
                jTextFieldPARTY_CITY.setText(add3);
             
                         
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        
        
        
        
    }//GEN-LAST:event_jTable1_PARTYNAME_CITYMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
          if(txtsearch.getText().length()>0)
        {
         try
                {
                      
                       String sql="select NAME as NAME,ADDRESS as ADDRESS,CITY AS CITY  from client_master where  NAME  LIKE '%"+txtsearch.getText()+"%'";
                             
                      pst=(PreparedStatement) con.prepareStatement(sql);
    
                     rs=pst.executeQuery();
                 jTable1_PARTYNAME_CITY.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                }
                catch(Exception e)
                {
                 JOptionPane.showMessageDialog(rootPane, e);
                }
    
        }
        else
        {
        GetRecord1();
        }
        
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButtonNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButtonNewMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        // TODO add your handling code here:
        if(!jTextField_challan.getText().equals(" "))
       {
           try{
            int P = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);
            if (P==0)
            {
                con=Connect.ConnectDB();
                String sql= "delete from new_Challan where CHALLAN_NO = " + jTextField_challan.getText() + "";
                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);

                reset();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }                                            

       }
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    private void jButtonShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShowDataMouseClicked
        // TODO add your handling code here:
        this.hide();
        NEW_CHALLAN_SHOWDATA obj=new NEW_CHALLAN_SHOWDATA();
        obj.setVisible(true);
         
    }//GEN-LAST:event_jButtonShowDataMouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
       
        String  UpdateQuery=null;     
              PreparedStatement ps = null;                              
       
              try{
            con=Connect.ConnectDB();
        

                    UpdateQuery="UPDATE new_challan SET Party_Name= ?,party_city=?,add_Date=?"
                            + ",Address=?,Item_name=?,Serial_no=?,Quantity=?,Price=? "
                            + "WHERE Party_Name=?";
                    
                    ps=con.prepareStatement(UpdateQuery);
                    
                
                    ps.setString(1,jTextFielPARTY_NAME.getText());
                    ps.setString(2,jTextFieldPARTY_CITY.getText());
                    
                      SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                    String addDate=dateFormat.format(jDateChooser1.getDate());
                    ps.setString(3,addDate);
                    
                    
                    ps.setString(4, jTextField_Address.getText());
                    
                   ps.setString(5,jTextFieldITEM_NAME.getText());
                    ps.setString(6, jTextFieldserial_no.getText());
                    
                  
                    
                    ps.setString(7, jTextField_Quantity.getText());
                     ps.setString(8, jTextFieldPrice.getText());
                     
   ps.setString(9, jTextFielPARTY_NAME.getText());
               
                    
                    ps.executeUpdate();
                   // Show_Products_In_JTable();
              
                
                      
                
            
            
            
        //    pst=con.prepareStatement(sql);
          //  pst.execute();
            JOptionPane.showMessageDialog(this,"Successfully Updated","Challan Number",JOptionPane.INFORMATION_MESSAGE);
            jButtonUpdate.setEnabled(false);

                }   
                 
              catch(HeadlessException | SQLException ex)
                 {
                         JOptionPane.showMessageDialog(this,ex);
                 }
                                             
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jLabel_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_itemMouseClicked
        // TODO add your handling code here:

        Item_Master_client_master mrp=new Item_Master_client_master();
        mrp.setVisible(true);

    }//GEN-LAST:event_jLabel_itemMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        jTextArea1.append("\t\t Challan No \n\n"+
                "Name:\t\t\t"+jTextFielPARTY_NAME.getText()+
        
                 "City:\t\t\t"+jTextFieldPARTY_CITY.getText()+"\n\n"+
                 "Date:\t\t\t"+jDateChooser1.getDate() +"\n\n"+
                  "Address:\t\t\t"+jTextField_Address.getText()+"\n\n"+
                  "Item Name:\t\t\t"+jTextFieldITEM_NAME.getText()+"\n\n"+
                 "Serial Number:\t\t\t"+jTextFieldserial_no.getText()+"\n\n"+
                   "Quantity :\t\t\t"+jTextField_Quantity.getText()+"\n\n"+                       
                "Price :\t\t\t"+jTextFieldPrice.getText()+ "\n"+  
                "=========================================="
          );
                

        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEW_CHALLAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEW_CHALLAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEW_CHALLAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEW_CHALLAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEW_CHALLAN().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton jButton1;
    javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNew;
    javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JButton jButtonUpdate;
    com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_item;
    private javax.swing.JLabel jLabelback_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1_PARTYNAME_CITY;
    private javax.swing.JTextArea jTextArea1;
    javax.swing.JTextField jTextFielPARTY_NAME;
    javax.swing.JTextArea jTextFieldITEM_NAME;
    public javax.swing.JTextField jTextFieldPARTY_CITY;
    javax.swing.JTextField jTextFieldPrice;
    javax.swing.JTextArea jTextField_Address;
    javax.swing.JTextField jTextField_Quantity;
    javax.swing.JTextField jTextField_challan;
    javax.swing.JTextField jTextFieldserial_no;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
