
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sahibnoorsingh
 */
    public class show_Challans extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    

    /**
     * Creates new form show_Challans
     */
    public show_Challans() {
        initComponents();
        Get_Data1();
       
    }

        private void Get_Data1()
        {
          con=Connect.ConnectDB();
             try{
                  String sql="select * from new_challan";
       
                  
                     pst=con.prepareStatement(sql);
                      rs= pst.executeQuery();
                      
                      
 
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
      
             catch(Exception e)
             {
            JOptionPane.showMessageDialog(null, e);
          
             }           
        
        
       }
    
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_search_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_search_date = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel_backbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel1.setText("By Name");

        jTextField_search_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_nameKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel2.setText("By Date");

        jTextField_search_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_dateKeyReleased(evt);
            }
        });

        jLabel_backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-arrow.png"))); // NOI18N
        jLabel_backbutton.setText("Back Button");
        jLabel_backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_backbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_backbutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_search_date, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_search_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_search_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        try{
        con=Connect.ConnectDB();
            int row= jTable1.getSelectedRow();
            String table_click= jTable1.getModel().getValueAt(row, 0).toString();
            String sql= "select new_challan.challan_no,new_challan.Party_Name,new_challan.Party_city,new_challan.Address,new_challan.challan_date,new_challan_details.Item_name,new_challan_details.Serial_no,new_challan_details.Quantity,new_challan_details.Price,new_challan_details.item_date,new_challan_details.Remarks from new_challan,new_challan_details	where new_challan.challan_no='" + table_click + "'";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            
            

            
            if(rs.next()){
                
                
             NEW_CHALLAN_REDESIGNED_copy frm=new  NEW_CHALLAN_REDESIGNED_copy();
             frm.setVisible(true);
       
               String add1=rs.getString("challan_no");
                frm.jTextField_challan.setText(add1);
                
                String add2=rs.getString("Party_Name");
                frm.jComboBox_PNAME.setSelectedItem(add2);
                
                String add3=rs.getString("Party_city");
                frm.jTextFieldPARTY_CITY.setText(add3);
             
               

                String add4=rs.getString("Address");
                frm.jTextField_address.setText(add4);
                
                 java.sql.Date add5=rs.getDate("challan_date");
                 frm.jDateChooser_challan.setDate(add5);
                 
                 String add6=rs.getString("Remarks");
                 frm.jTextArea_remarks.setText(add6);
                 
                 
                 
                String sql2= "select u_no,Item_name,Serial_no,Quantity,Price,item_date from new_challan_details where challan_no='"+table_click +"'  ";
                ResultSet rs=pst.executeQuery(sql2);
                frm.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    this.hide();  
       //   ResultSet res = pst.executeQuery("select new_challan.challan_no,new_challan.Party_Name,new_challan.Party_city,new_challan.Address,new_challan.challan_date,new_challan_details.Item_name,new_challan_details.Serial_no,new_challan_details.Quantity,new_challan_details.Price,new_challan_details.item_date from new_challan,new_challan_details where new_challan.challan_no='" + table_click + "'"); 
         //  ResultSetMetaData metaData = rs.getMetaData();
           //      frm.jTable1.setModel(DbUtils.resultSetToTableModel(res));
                
                
                
               
        // String table_click2= jTable1.getModel().getValueAt(row, 0).toString();
       //  String sql2= "select new_challan_details.Item_name,new_challan_details.Serial_no,new_challan_details.Quantity,new_challan_details.Price,new_challan_details.item_date from new_challan,new_challan_details where  new_challan_details.challan_no ='" + table_click + "' " ;
             
       
             //    pst=con.prepareStatement(sql);
               //  rs=  pst.executeQuery();
              
                 //ResultSet  rst = pst.executeQuery();
                 //
              
                
                
            //    SimpleDateFormat  dateFormat=new SimpleDateFormat("MMM d, yyyy");

            // Date add5=rs.getDate("challan_date");
             //frm.jDateChooser_challan.setDate(add5);
              
              
                     
   
 
             
          
       
              
          
         
             // java.sql.Date add10=rs.getDate("item_date");
              //frm.jDateChooser_item.setDate(add10);
              
             
            }
            
        }
        
        
        
       catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_search_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_nameKeyReleased
        // TODO add your handling code here:
                if(jTextField_search_name.getText().length()>0)
        {
         try
                {
                      
                       String sql="SELECT *  from  new_challan WHERE Party_Name LIKE '%"+jTextField_search_name.getText()+"%'";
                             
                      pst=(PreparedStatement) con.prepareStatement(sql);
    
                     rs=pst.executeQuery();
                 jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                }
                catch(Exception e)
                {
                 JOptionPane.showMessageDialog(rootPane, e);
                }
    
        }
        else
        {
        Get_Data1();
        }
        
        
    }//GEN-LAST:event_jTextField_search_nameKeyReleased

    private void jTextField_search_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_dateKeyReleased
        // TODO add your handling code here:
            if(jTextField_search_date.getText().length()>0)
        {
         try
                {
                      
                       String sql="SELECT *  from  new_challan WHERE challan_date LIKE '%"+jTextField_search_date.getText()+"%'";
                             
                      pst=(PreparedStatement) con.prepareStatement(sql);
    
                     rs=pst.executeQuery();
                 jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                            
                }
                catch(Exception e)
                {
                 JOptionPane.showMessageDialog(rootPane, e);
                }
    
        }
        else
        {
        Get_Data1();
        }
        
        
        
        
    }//GEN-LAST:event_jTextField_search_dateKeyReleased

    private void jLabel_backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backbuttonMouseClicked
        // TODO add your handling code here:

        this.hide();
        NEW_CHALLAN_REDESIGNED obj=new NEW_CHALLAN_REDESIGNED();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_Challans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_Challans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_Challans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_Challans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_Challans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_backbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_search_date;
    private javax.swing.JTextField jTextField_search_name;
    // End of variables declaration//GEN-END:variables
}
